/*
 * EdmundsVehicleAPI.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 01/27/2016
 */
using System;

namespace EdmundsVehicleAPI.PCL
{
    public partial class Configuration
    {
        //The base Uri for API calls
        public static string BaseUri = "https://api.edmunds.com/";

        //TODO: Replace the ApiKey with an appropriate value
        public static string ApiKey = "u7m5dbqkuyfuh6s3ud557tv5";
    }
}