/*
 * EdmundsVehicleAPI.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 01/27/2016
 */
using System;
using EdmundsVehicleAPI.PCL.Controllers;

namespace EdmundsVehicleAPI.PCL
{
    public partial class EdmundsVehicleAPIClient
    {

        /// <summary>
        /// Singleton access to SpecVehicleMake controller
        /// </summary>
        public SpecVehicleMakeController SpecVehicleMake
        {
            get
            {
                return SpecVehicleMakeController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to SpecVehicleModel controller
        /// </summary>
        public SpecVehicleModelController SpecVehicleModel
        {
            get
            {
                return SpecVehicleModelController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to SpecVehicleModelYear controller
        /// </summary>
        public SpecVehicleModelYearController SpecVehicleModelYear
        {
            get
            {
                return SpecVehicleModelYearController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to SpecVehicleStyle controller
        /// </summary>
        public SpecVehicleStyleController SpecVehicleStyle
        {
            get
            {
                return SpecVehicleStyleController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to SpecVehicleColorsAndOptions controller
        /// </summary>
        public SpecVehicleColorsAndOptionsController SpecVehicleColorsAndOptions
        {
            get
            {
                return SpecVehicleColorsAndOptionsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to SpecVehicleEngineAmpTransmission controller
        /// </summary>
        public SpecVehicleEngineAmpTransmissionController SpecVehicleEngineAmpTransmission
        {
            get
            {
                return SpecVehicleEngineAmpTransmissionController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to SpecVehicleEquipment controller
        /// </summary>
        public SpecVehicleEquipmentController SpecVehicleEquipment
        {
            get
            {
                return SpecVehicleEquipmentController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to SpecVehicleSquishVINs controller
        /// </summary>
        public SpecVehicleSquishVINsController SpecVehicleSquishVINs
        {
            get
            {
                return SpecVehicleSquishVINsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to SpecVehicleConfiguration controller
        /// </summary>
        public SpecVehicleConfigurationController SpecVehicleConfiguration
        {
            get
            {
                return SpecVehicleConfigurationController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to SpecVINDecoding controller
        /// </summary>
        public SpecVINDecodingController SpecVINDecoding
        {
            get
            {
                return SpecVINDecodingController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to MediaVehiclePhoto controller
        /// </summary>
        public MediaVehiclePhotoController MediaVehiclePhoto
        {
            get
            {
                return MediaVehiclePhotoController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to PricingTrueCostToOwnTCO controller
        /// </summary>
        public PricingTrueCostToOwnTCOController PricingTrueCostToOwnTCO
        {
            get
            {
                return PricingTrueCostToOwnTCOController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to PricingTrueMarketValueTMV controller
        /// </summary>
        public PricingTrueMarketValueTMVController PricingTrueMarketValueTMV
        {
            get
            {
                return PricingTrueMarketValueTMVController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to PricingIncentivesAndRebates controller
        /// </summary>
        public PricingIncentivesAndRebatesController PricingIncentivesAndRebates
        {
            get
            {
                return PricingIncentivesAndRebatesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ContentEdmundsCarRatings controller
        /// </summary>
        public ContentEdmundsCarRatingsController ContentEdmundsCarRatings
        {
            get
            {
                return ContentEdmundsCarRatingsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ContentVehicleRatingsAndReviews controller
        /// </summary>
        public ContentVehicleRatingsAndReviewsController ContentVehicleRatingsAndReviews
        {
            get
            {
                return ContentVehicleRatingsAndReviewsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ServiceVehicleMaintenance controller
        /// </summary>
        public ServiceVehicleMaintenanceController ServiceVehicleMaintenance
        {
            get
            {
                return ServiceVehicleMaintenanceController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ServiceVehicleRecalls controller
        /// </summary>
        public ServiceVehicleRecallsController ServiceVehicleRecalls
        {
            get
            {
                return ServiceVehicleRecallsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ServiceVehicleServiceBulletin controller
        /// </summary>
        public ServiceVehicleServiceBulletinController ServiceVehicleServiceBulletin
        {
            get
            {
                return ServiceVehicleServiceBulletinController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ServiceVehicleNotes controller
        /// </summary>
        public ServiceVehicleNotesController ServiceVehicleNotes
        {
            get
            {
                return ServiceVehicleNotesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ServiceLocalLaborRate controller
        /// </summary>
        public ServiceLocalLaborRateController ServiceLocalLaborRate
        {
            get
            {
                return ServiceLocalLaborRateController.Instance;
            }
        }

        /// <summary>
        /// Client constructor
        /// </summary>
        public EdmundsVehicleAPIClient(string apiKey)
        {
            Configuration.ApiKey = apiKey;
        }
    }
}